-record(alarm, {class_id,
                alarm_key,
			    alarm_name,
			    alarm_alias,
			    alarm_state,
				manager, %from event manager
                agent,
                node_id,
			    source,
			    source_class,
			    severity,
			    summary,
				sequence_no,
			    priority = 2,
                graded = 0,
			    occur_count = 1,
			    probable_cause,
			    specific_problem,
			    additional_information,
                cleared,
			    cleared_user,
			    cleared_time,
			    first_occurrence,
			    last_occurrence,
				order_state,
                root_cause,
                cause_type = 2,
				timestamp, %timestamp used to compare
				vars}). %vars from event


