# encoding: utf-8


cn = {
    'nodes': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'category.alias': u'节点类型',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'area.full_name': u'所属区域',
        'last_check': u'上次同步',
        'summary': u'状态信息',
        },
    'switches': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.city_name': u'地市',
        'area.town_name': u'区县',
        'area.entrance_name': u'接入点',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'routers': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.city_name': u'地市',
        'area.town_name': u'区县',
        'area.entrance_name': u'接入点',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'olts': {
        'status': u'状态',
        'name': u'名称',
        'category.alias': u'节点类型',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.full_name': u'所属区域',
        'onu_count_plan': u'ONU数量',
        'onu_count_unplan': u'未规划ONU',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'snmp_ver': u'SNMP版本',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'onus': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.city_name': u'地市',
        'area.town_name': u'区县',
        'area.branch_name': u'分局',
        'area.entrance_name': u'接入点',
        'olt.name': u'OLT名称',
        'olt.addr': u'OLT IP',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    }