# encoding: utf-8


cn = {
    'cities': {
        'parent_id': u'所属区域',
        'name': u'地市名称',
        'alias': u'地市别名',
        'longitude': u'经度',
        'latitude': u'纬度',
        'remark': u'备注',
        'town_count': u'区县',
        'branch_count': u'分局',
        'entrance_count': u'接入点',
        'total_count': u'节点',
        'router_count': u'路由器',
        'switch_count': u'交换机',
        'olt_count': u'OLT',
        'onu_count': u'ONU',
        'eoc_count': u'EOC',
        'cpe_count': u'CPE',
        },
    'towns': {
        'parent_id': u'所属区域',
        'name': u'区县名称',
        'alias': u'区县别名',
        'longitude': u'经度',
        'latitude': u'纬度',
        'remark': u'备注',
        'branch_count': u'分局',
        'entrance_count': u'接入点',
        'total_count': u'节点',
        'router_count': u'路由器',
        'switch_count': u'交换机',
        'olt_count': u'OLT',
        'onu_count': u'ONU',
        'eoc_count': u'EOC',
        'cpe_count': u'CPE',
        },
    'branches': {
        'parent_id': u'所属区域',
        'name': u'分局名称',
        'alias': u'分局别名',
        'longitude': u'经度',
        'latitude': u'纬度',
        'remark': u'备注',
        'entrance_count': u'接入点',
        'total_count': u'节点',
        'router_count': u'路由器',
        'switch_count': u'交换机',
        'olt_count': u'OLT',
        'onu_count': u'ONU',
        'eoc_count': u'EOC',
        'cpe_count': u'CPE',
        },
    'entrances': {
        'parent_id': u'所属区域',
        'name': u'接入点名称',
        'alias': u'接入点别名',
        'longitude': u'经度',
        'latitude': u'纬度',
        'remark': u'备注',
        'total_count': u'节点',
        'router_count': u'路由器',
        'switch_count': u'交换机',
        'olt_count': u'OLT',
        'onu_count': u'ONU',
        'eoc_count': u'EOC',
        'cpe_count': u'CPE',
        },
    'nodes': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'category.alias': u'节点类型',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'area.full_name': u'所属区域',
        'last_check': u'上次同步',
        'summary': u'状态信息',
        },
    'switches': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.full_name': u'所属区域',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'routers': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.full_name': u'所属区域',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'olts': {
        'status': u'状态',
        'name': u'名称',
        'category.alias': u'节点类型',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.full_name': u'所属区域',
        'onu_count_plan': u'ONU数量',
        'onu_count_unplan': u'未规划ONU',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'snmp_ver': u'SNMP版本',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'onus': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.full_name': u'所属区域',
        'olt.name': u'OLT名称',
        'olt.addr': u'OLT IP',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'eocs': {
        'status': u'状态',
        'name': u'名称',
        'category.alias': u'节点类型',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.full_name': u'所属区域',
        'cpe_count_plan': u'CPE数量',
        'cpe_count_unplan': u'未规划CPE',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'snmp_ver': u'SNMP版本',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    'cpes': {
        'status': u'状态',
        'name': u'名称',
        'alias': u'别名',
        'addr': u'IP地址',
        'area.full_name': u'所属区域',
        'eoc.name': u'EOC名称',
        'eoc.addr': u'EOC IP',
        'vendor.alias': u'厂商',
        'model.alias': u'型号',
        'mask': u'子网掩码',
        'snmp_comm': u'读团体名',
        'snmp_wcomm': u'写团体名',
        'last_check': u'上次同步',
        'location': u'位置',
        'remark': u'备注',
        },
    }